# Constants as defaults in primitives
bool bool_value Constants::BOOL_CONST
byte byte_value Constants::BYTE_CONST
char char_value Constants::CHAR_CONST
float32 float32_value Constants::FLOAT32_CONST
float64 float64_value Constants::FLOAT64_CONST
int8 int8_value Constants::INT8_CONST
uint8 uint8_value Constants::UINT8_CONST
int16 int16_value Constants::INT16_CONST
uint16 uint16_value Constants::UINT16_CONST
int32 int32_value Constants::INT32_CONST
uint32 uint32_value Constants::UINT32_CONST
int64 int64_value Constants::INT64_CONST
uint64 uint64_value Constants::UINT64_CONST

# Constants as defaults in arrays
bool[<=3] bool_values_const [0, Constants::BOOL_CONST]
byte[<=3] byte_values_const [0, Constants::BYTE_CONST]
char[<=3] char_values_const [0, Constants::CHAR_CONST]
float32[<=3] float32_values_const [0, Constants::FLOAT32_CONST]
float64[<=3] float64_values_const [0, Constants::FLOAT64_CONST]
int8[<=3] int8_values_const [0, Constants::INT8_CONST]
uint8[<=3] uint8_values_const [0, Constants::UINT8_CONST]
int16[<=3] int16_values_const [0, Constants::INT16_CONST]
uint16[<=3] uint16_values_const [0, Constants::UINT16_CONST]
int32[<=3] int32_values_const [0, Constants::INT32_CONST]
uint32[<=3] uint32_values_const [0, Constants::UINT32_CONST]
int64[<=3] int64_values_const [0, Constants::INT64_CONST]
uint64[<=3] uint64_values_const [0, Constants::UINT64_CONST]
